//! Per-project setup script runner. Each project can store a bash blob in
//! `projects.setup_script`; when a card moves to "To Do" we create its
//! worktree and then run that script inside it (typical use: `bun install`,
//! `cp .env`, etc).
//!
//! Streams stdout/stderr line-by-line via Tauri events so the frontend can
//! display the output in a dedicated terminal-drawer tab, and emits an
//! exit event with the script's status code so the board store can decide
//! whether to spawn the agent or revert the card.

use std::process::Stdio;

use serde::Serialize;
use tauri::{AppHandle, Emitter, State};
use tokio::io::{AsyncBufReadExt, BufReader};
use tokio::process::Command;
use tokio::sync::mpsc;

use crate::db::Db;
use crate::error::{AppError, AppResult};

#[derive(Serialize, Clone)]
#[serde(rename_all = "camelCase")]
struct DataPayload {
    run_id: String,
    line: String,
    stream: &'static str, // "stdout" | "stderr"
}

#[derive(Serialize, Clone)]
#[serde(rename_all = "camelCase")]
struct ExitPayload {
    run_id: String,
    code: Option<i32>,
    /// "clean" — process exited (zero or non-zero); "spawn_error" — bash
    /// itself couldn't start; "await_error" — IPC failure waiting for exit.
    reason: &'static str,
}

/// Spawn the project's `setup_script` inside `worktree_path` and stream its
/// output on `setup://run/<run_id>/data`, finishing with an event on
/// `setup://run/<run_id>/exit`. `run_id` is generated by the caller so it
/// can subscribe to both channels BEFORE invoking this command.
///
/// Env vars the script can rely on:
///   - `SOURCE_REPO`       — absolute path of the original project repo
///   - `WORKTREE_PATH`     — absolute path of the worktree being set up
#[tauri::command]
pub async fn setup_run_start(
    app: AppHandle,
    db: State<'_, Db>,
    run_id: String,
    project_id: String,
    worktree_path: String,
) -> AppResult<()> {
    let (script, source_repo) = db.with(|conn| {
        let row: (Option<String>, String) = conn.query_row(
            "SELECT setup_script, repo_path FROM projects WHERE id = ?1",
            [&project_id],
            |r| Ok((r.get(0)?, r.get(1)?)),
        )?;
        Ok(row)
    })?;

    let script = match script {
        Some(s) if !s.trim().is_empty() => s,
        _ => return Err(AppError::msg("project has no setup script configured")),
    };

    // The actual streaming runs in a detached task — the IPC call returns
    // immediately and the caller awaits the exit event.
    let app_for_task = app.clone();
    tokio::spawn(async move {
        run_script(app_for_task, run_id, worktree_path, source_repo, script).await;
    });

    Ok(())
}

async fn run_script(
    app: AppHandle,
    run_id: String,
    worktree_path: String,
    source_repo: String,
    script: String,
) {
    let data_event = format!("setup://run/{run_id}/data");
    let exit_event = format!("setup://run/{run_id}/exit");

    // Echo the script so the user can see exactly what's running — same
    // affordance as a regular shell prompt. Multi-line scripts get
    // prefixed so they read like a heredoc.
    let echo = if script.contains('\n') {
        format!("$ bash -lc <<'EOF'\n{script}\nEOF")
    } else {
        format!("$ {script}")
    };
    let _ = app.emit(
        &data_event,
        DataPayload {
            run_id: run_id.clone(),
            line: echo,
            stream: "stdout",
        },
    );

    let mut cmd = Command::new("bash");
    cmd.arg("-lc")
        .arg(&script)
        .current_dir(&worktree_path)
        .env("SOURCE_REPO", &source_repo)
        .env("WORKTREE_PATH", &worktree_path)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .stdin(Stdio::null());

    let mut child = match cmd.spawn() {
        Ok(c) => c,
        Err(e) => {
            let _ = app.emit(
                &data_event,
                DataPayload {
                    run_id: run_id.clone(),
                    line: format!("[dispatch] failed to spawn bash: {e}"),
                    stream: "stderr",
                },
            );
            let _ = app.emit(
                &exit_event,
                ExitPayload {
                    run_id,
                    code: None,
                    reason: "spawn_error",
                },
            );
            return;
        }
    };

    // unwrap is safe — we set stdout/stderr to piped() above.
    let stdout = child.stdout.take().unwrap();
    let stderr = child.stderr.take().unwrap();

    let (tx, mut rx) = mpsc::channel::<(&'static str, String)>(256);

    let tx_out = tx.clone();
    tokio::spawn(async move {
        let mut r = BufReader::new(stdout).lines();
        while let Ok(Some(line)) = r.next_line().await {
            if tx_out.send(("stdout", line)).await.is_err() {
                break;
            }
        }
    });
    let tx_err = tx;
    tokio::spawn(async move {
        let mut r = BufReader::new(stderr).lines();
        while let Ok(Some(line)) = r.next_line().await {
            if tx_err.send(("stderr", line)).await.is_err() {
                break;
            }
        }
    });

    let (code, reason): (Option<i32>, &'static str) = loop {
        match rx.recv().await {
            Some((stream, line)) => {
                let _ = app.emit(
                    &data_event,
                    DataPayload {
                        run_id: run_id.clone(),
                        line,
                        stream,
                    },
                );
            }
            None => match child.wait().await {
                Ok(status) => break (status.code(), "clean"),
                Err(_) => break (None, "await_error"),
            },
        }
    };

    let _ = app.emit(
        &exit_event,
        ExitPayload {
            run_id,
            code,
            reason,
        },
    );
}
